/* Optional rendered analysis checks. Use only a disposable live session.
   NODE_PATH=/path/to/node_modules node tests/analysis-smoke.cjs http://127.0.0.1:PORT /tmp/analysis-qa */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {execFileSync}=require('node:child_process');
const [url,output]=process.argv.slice(2);
if(!url||!output||!/^http:\/\/127\.0\.0\.1:\d+\/?$/.test(url))throw Error('Provide a disposable loopback session URL and output directory.');
const origin=url.replace(/\/$/,''),copy=value=>JSON.parse(JSON.stringify(value)),results=[],errors=[];
const fixture={schemaVersion:1,revision:1,title:'Fictional analysis smoke test',question:'Could a fictional workshop cover its costs?',context:'Disposable QA fixture. The teaching model is not evidence about a real event.',nextQuestion:'',nodes:[{id:'root',parentId:null,label:'Explore workshop viability',kind:'question',status:'open',notes:'No recommendation.',method:'issue'},{id:'economics',parentId:'root',label:'What attendance breaks even?',kind:'question',status:'uncertain',notes:'Demand remains unknown.',method:'driver',relation:{type:'part-of'}}],decision:{recommendation:'',rationale:'',uncertainties:[],nextSteps:[]}};
async function read(){const response=await fetch(origin+'/api/state');assert.equal(response.status,200);return response.json()}
async function put(value){const current=await read();const response=await fetch(origin+'/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:current.revision,state:value})});assert.equal(response.status,200,await response.clone().text());return response.json()}
async function save(page){const response=page.waitForResponse(r=>r.url().endsWith('/api/state')&&r.request().method()==='PUT');await page.locator('#analysis-save').click();assert.equal((await response).status(),200);await page.waitForFunction(()=>document.querySelector('#analysis-save').disabled&&document.querySelector('#analysis-discard').hidden);return read()}
async function exportFile(page,format,name){await page.locator('details.export summary').click();const pending=page.waitForEvent('download');await page.locator('[data-export="'+format+'"]').click();const target=path.join(output,name);await(await pending).saveAs(target);return target}
async function result(page,id,scenario){return page.locator('[data-result-id="'+id+'"] [data-scenario="'+scenario+'"]').innerText()}
async function open(page){await page.goto(origin);if(await page.locator('#quick-start').isVisible())await page.locator('#tour-skip').click();await page.locator('.tree-node[data-id="economics"]').click();await page.locator('#analysis-open').click()}
(async()=>{await fs.mkdir(output,{recursive:true});await put(fixture);const browser=await chromium.launch({headless:true});try{const context=await browser.newContext({viewport:{width:1400,height:1050},reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await open(page);const untouched=await read();assert.equal(await page.locator('#analysis-model-choice').isHidden(),true);assert.match(await page.locator('#analysis-numbers-body').innerText(),/Start with a number/);assert.deepEqual(await read(),untouched);await page.locator('#analysis-model-example').click();assert.deepEqual(await read(),untouched,'Clicking the fictional example opens a draft only');assert.match(await result(page,'attendance','base'),/^8\nattendees$/);assert.match(await result(page,'attendance','low'),/^7\nattendees$/);await page.locator('#analysis-value-fixed_cost-base').fill('180');assert.match(await result(page,'attendance','base'),/^12\nattendees$/);assert.match(await result(page,'attendance','low'),/^7\nattendees$/);const first=await save(page);assert.equal(first.analysis.models[0].nodeId,'economics');assert.equal(first.analysis.models[0].variables.find(v=>v.id==='fixed_cost').values.base,180);results.push('Explicit fictional example stays a draft until save, links to the selected branch, and recalculates the affected scenario.');

await page.locator('#analysis-value-fixed_cost-low').fill('');assert.match(await result(page,'attendance','low'),/Missing low input/);await page.locator('#analysis-value-ticket_price-base').fill('5');assert.match(await result(page,'attendance','base'),/Division by zero/);const formula=page.locator('[data-variable-id="attendance"] .analysis-formula');await formula.fill('ceil(unknown_input / contribution)');assert.match(await result(page,'attendance','high'),/Missing variable/);await formula.fill('attendance + 1');assert.match(await result(page,'attendance','high'),/Circular dependency/);await formula.fill('globalThis.alert(1)');assert.match(await result(page,'attendance','high'),/Unsupported formula syntax/);await page.locator('#analysis-discard').click();await page.locator('#analysis-discard').waitFor({state:'hidden'});assert.match(await result(page,'attendance','base'),/^12\nattendees$/);assert.deepEqual(await read(),first);results.push('Missing inputs, division by zero, absent names, cycles and executable-looking formulas show errors rather than zero; discard restores saved values.');

const parityModels=[{id:'math',title:'Math checks',outputId:'result',variables:[{id:'x',label:'X',unit:'',basis:'Fixture',values:{low:1.25,base:-2.4,high:null}},{id:'y',label:'Y',unit:'',basis:'Fixture',values:{low:2,base:4,high:0}},{id:'result',label:'Result',unit:'',basis:'Fixture',formula:'ceil((x * 3 + floor(-y)) / 2)'},{id:'bad',label:'Missing reference',unit:'',basis:'Fixture',formula:'absent + x'},{id:'divide',label:'Divide',unit:'',basis:'Fixture',formula:'1 / y'}]}];for(const formula of ['1 / (1e308 * 2)', '(' .repeat(35)+'1'+')'.repeat(35), 'ceil(1,)', '01', '.5e2', '-'.repeat(31)+'1', '1+'.repeat(31)+'1', 'floor(-2.5)', '1e309'])parityModels.push({id:'edge',title:'Expression boundary',outputId:'result',variables:[{id:'result',label:'Result',unit:'',basis:'Fixture',formula}]});parityModels.push({id:'names',title:'Identifier safety',outputId:'constructor',variables:[{id:'__proto__',label:'Valid identifier',unit:'',basis:'Fixture',values:{low:2,base:3,high:4}},{id:'constructor',label:'Dependent identifier',unit:'',basis:'Fixture',formula:'__proto__ * 2'}]});for(const model of parityModels){const front=JSON.parse(await page.evaluate(m=>JSON.stringify(evaluateAnalysisModel(m)),model));const backend=JSON.parse(execFileSync('python3',['-c',"import sys,json; sys.path.insert(0,'scripts'); from analysis import evaluate_model; print(json.dumps(evaluate_model(json.load(sys.stdin))))"],{cwd:path.resolve(__dirname,'..'),input:JSON.stringify(model),encoding:'utf8'}));assert.deepEqual(front.values,backend.values);for(const id of Object.keys(front.errors))for(const scenario of front.scenarios)assert.equal(Boolean(front.errors[id][scenario]),Boolean(backend.errors[id][scenario]));}results.push('The standalone browser evaluator matches backend scenario values and error presence on arithmetic, rounding, missing inputs and division.');

await page.locator('#analysis-value-fixed_cost-base').fill('240');const external=await read();external.nodes[0].notes='Another editor changed the question context.';external.analysis.models[0].description='The other editor preserved the model.';const externalSaved=await put(external);await page.locator('#analysis-conflict').waitFor({state:'visible'});assert.equal(await page.locator('#analysis-save').isDisabled(),true);assert.equal(await page.locator('#analysis-value-fixed_cost-base').inputValue(),'240');await page.locator('#analysis-refresh').click();assert.equal(await page.locator('#analysis-value-fixed_cost-base').inputValue(),'240','Refresh cannot discard an unkept draft');assert.deepEqual(await read(),externalSaved);await page.locator('#analysis-discard').click();await page.locator('#analysis-discard').waitFor({state:'hidden'});assert.equal(await page.locator('#analysis-value-fixed_cost-base').inputValue(),'180');assert.equal(await page.locator('#analysis-model-description').inputValue(),'The other editor preserved the model.');assert.equal(await page.locator('#analysis-conflict').isHidden(),true);results.push('An external revision blocks stale analysis saves without losing inputs; explicit discard loads the other editor’s analysis and preserves tree edits.');

await page.locator('#analysis-tab-workplan').click();await page.locator('#analysis-work-add').click();const work=page.locator('[data-work-id]');assert.equal(await work.getByLabel('Owner',{exact:true}).inputValue(),'');assert.equal(await work.getByLabel('Due date',{exact:true}).inputValue(),'');await work.getByLabel('Work to do',{exact:true}).fill('Check venue costs');await work.getByLabel('How to analyse it',{exact:true}).fill('Compare the two available quotes.');await work.getByLabel('Work status',{exact:true}).selectOption('done');await work.getByLabel('What we found',{exact:true}).fill('The available quote excludes staffing.');const completed=await save(page);assert.equal(completed.analysis.workplan[0].status,'done');assert.equal(completed.analysis.workplan[0].nodeId,'economics');assert.equal(completed.nodes.find(n=>n.id==='economics').status,'uncertain');results.push('A completed, branch-linked work item keeps blank owner/date and leaves the tree’s uncertain claim unchanged.');

await page.locator('#analysis-tab-brief').click();await page.locator('#analysis-brief-situation').fill('We are considering one workshop.');await page.locator('#analysis-brief-complication').fill('The costs and demand are uncertain.');await page.locator('#analysis-brief-answer').fill('Check demand before committing.');await page.getByRole('button',{name:'Add supporting section',exact:true}).click();const section=page.locator('[data-section-id]');await section.getByLabel('Claim',{exact:true}).fill('Cost coverage is a hurdle, not a sales forecast.');await section.getByLabel('Reasoning and evidence',{exact:true}).fill('These fictional inputs do not establish willingness to pay.');await section.locator('summary').click();await section.getByRole('button',{name:'Link a calculated value',exact:true}).click();assert.match(await section.innerText(),/Break-even attendance \(base\): 12 attendees/);const briefSaved=await save(page),basis=briefSaved.analysis.brief.basedOnRevision;assert.equal(briefSaved.revision,basis+1);assert.equal(await page.locator('#analysis-brief-stale').isHidden(),true);await page.locator('#analysis-tab-numbers').click();await page.locator('#analysis-value-fixed_cost-base').fill('150');const changedNumbers=await save(page);assert.equal(changedNumbers.analysis.brief.basedOnRevision,basis);await page.locator('#analysis-tab-brief').click();assert.equal(await page.locator('#analysis-brief-stale').isVisible(),true);assert.equal(await page.locator('#analysis-brief-answer').inputValue(),'Check demand before committing.');assert.match(await page.locator('[data-section-id]').innerText(),/Break-even attendance \(base\): 10 attendees/);await page.getByRole('button',{name:'I have checked this wording',exact:true}).click();const checked=await save(page);assert.equal(checked.analysis.brief.basedOnRevision,checked.revision-1);assert.equal(await page.locator('#analysis-brief-stale').isHidden(),true);results.push('Brief wording stays literal; number edits update referenced values and mark the old brief stale without refreshing its basis. An explicit wording check records a fresh revision.');

await page.locator('#analysis-tab-numbers').click();await page.getByRole('button',{name:'Remove model',exact:true}).click();assert.match(await page.locator('#toast').innerText(),/referenced in the brief/);assert.equal((await read()).analysis.models.length,1);await page.locator('#analysis-close').click();await page.locator('#inspect-toggle').click();await page.locator('#delete').click();assert.match(await page.locator('#toast').innerText(),/used by a model, work item or brief/);assert.equal((await read()).nodes.length,2);await page.locator('#close-details').click();results.push('Referenced models and tree branches cannot be deleted until their analysis references are deliberately removed or relinked.');

const html=await exportFile(page,'html','analysis.html'),md=await exportFile(page,'md','analysis.md');const markdown=await fs.readFile(md,'utf8');assert.match(markdown,/Fictional workshop break-even/);assert.match(markdown,/Check venue costs/);assert.match(markdown,/Cost coverage is a hurdle/);assert.match(markdown,/Break-even attendance \(base\): 10 attendees/);const offlineContext=await browser.newContext({viewport:{width:1400,height:1050}}),standalone=await offlineContext.newPage();standalone.on('pageerror',e=>errors.push(e.message));await standalone.goto(pathToFileURL(html).href);assert.equal(await standalone.locator('dialog[open]').count(),0);await standalone.locator('#analysis-open').click();assert.match(await result(standalone,'attendance','base'),/^10\nattendees$/);await standalone.locator('#analysis-value-fixed_cost-base').fill('195');assert.match(await result(standalone,'attendance','base'),/^13\nattendees$/);await standalone.locator('#analysis-save').click();await standalone.waitForFunction(()=>document.querySelector('#analysis-discard').hidden);await standalone.locator('#analysis-tab-brief').click();assert.equal(await standalone.locator('#analysis-brief-stale').isVisible(),true);await standalone.locator('#analysis-close').click();const offlineJSON=await exportFile(standalone,'json','analysis-offline.json');assert.equal(JSON.parse(await fs.readFile(offlineJSON,'utf8')).analysis.models[0].variables.find(v=>v.id==='fixed_cost').values.base,195);assert.equal((await read()).analysis.models[0].variables.find(v=>v.id==='fixed_cost').values.base,150);results.push('HTML and Markdown retain models, workplan and brief; offline calculations match, local edits export and never change the live session.');

await page.locator('#analysis-open').click();await page.locator('#analysis-tab-brief').click();const printPending=page.waitForEvent('download');await page.getByRole('button',{name:'Printable brief',exact:true}).click();const briefFile=path.join(output,'printable-brief.html');await(await printPending).saveAs(briefFile);assert.match(await fs.readFile(briefFile,'utf8'),/Check demand before committing/);await page.screenshot({path:path.join(output,'analysis-brief.png')});await page.setViewportSize({width:390,height:844});await page.locator('#analysis-tab-numbers').click();await page.screenshot({path:path.join(output,'analysis-mobile.png')});const bounds=await page.locator('#analysis-panel').boundingBox();assert.ok(bounds.width<=390&&bounds.x>=0);assert.equal(await page.locator('#analysis-panel').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true,'Analysis must not require horizontal page scrolling');assert.deepEqual(errors,[]);results.push('The printable brief preserves saved wording, and the workspace remains bounded and usable at phone width.');await fs.writeFile(path.join(output,'results.json'),JSON.stringify({passed:true,checks:results},null,2)+'\n');console.log(JSON.stringify({passed:true,checks:results},null,2));}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
